"""empty message

Revision ID: 5725e24cb7
Revises: None
Create Date: 2014-09-28 13:23:56.076000

"""

# revision identifiers, used by Alembic.
revision = '5725e24cb7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('introduce_myself', sa.Text(), nullable=True),
    sa.Column('exp01', sa.String(length=255), nullable=True),
    sa.Column('exp02', sa.String(length=255), nullable=True),
    sa.Column('exp03', sa.String(length=255), nullable=True),
    sa.Column('exp04', sa.String(length=255), nullable=True),
    sa.Column('exp05', sa.String(length=255), nullable=True),
    sa.Column('exp06', sa.String(length=255), nullable=True),
    sa.Column('exp07', sa.String(length=255), nullable=True),
    sa.Column('exp08', sa.String(length=255), nullable=True),
    sa.Column('exp09', sa.String(length=255), nullable=True),
    sa.Column('exp10', sa.String(length=255), nullable=True),
    sa.Column('exp11', sa.String(length=255), nullable=True),
    sa.Column('exp12', sa.String(length=255), nullable=True),
    sa.Column('exp13', sa.String(length=255), nullable=True),
    sa.Column('exp14', sa.String(length=255), nullable=True),
    sa.Column('exp15', sa.String(length=255), nullable=True),
    sa.Column('exp16', sa.String(length=255), nullable=True),
    sa.Column('exp17', sa.String(length=255), nullable=True),
    sa.Column('exp18', sa.String(length=255), nullable=True),
    sa.Column('exp19', sa.String(length=255), nullable=True),
    sa.Column('exp20', sa.String(length=255), nullable=True),
    sa.Column('title01', sa.String(length=255), nullable=True),
    sa.Column('title02', sa.String(length=255), nullable=True),
    sa.Column('title03', sa.String(length=255), nullable=True),
    sa.Column('title04', sa.String(length=255), nullable=True),
    sa.Column('title05', sa.String(length=255), nullable=True),
    sa.Column('title06', sa.String(length=255), nullable=True),
    sa.Column('title07', sa.String(length=255), nullable=True),
    sa.Column('title08', sa.String(length=255), nullable=True),
    sa.Column('title09', sa.String(length=255), nullable=True),
    sa.Column('title10', sa.String(length=255), nullable=True),
    sa.Column('title11', sa.String(length=255), nullable=True),
    sa.Column('title12', sa.String(length=255), nullable=True),
    sa.Column('title13', sa.String(length=255), nullable=True),
    sa.Column('title14', sa.String(length=255), nullable=True),
    sa.Column('title15', sa.String(length=255), nullable=True),
    sa.Column('title16', sa.String(length=255), nullable=True),
    sa.Column('title17', sa.String(length=255), nullable=True),
    sa.Column('title18', sa.String(length=255), nullable=True),
    sa.Column('title19', sa.String(length=255), nullable=True),
    sa.Column('title20', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('exp01', sa.String(length=255), nullable=True),
    sa.Column('exp02', sa.String(length=255), nullable=True),
    sa.Column('exp03', sa.String(length=255), nullable=True),
    sa.Column('exp04', sa.String(length=255), nullable=True),
    sa.Column('exp05', sa.String(length=255), nullable=True),
    sa.Column('exp06', sa.String(length=255), nullable=True),
    sa.Column('exp07', sa.String(length=255), nullable=True),
    sa.Column('exp08', sa.String(length=255), nullable=True),
    sa.Column('exp09', sa.String(length=255), nullable=True),
    sa.Column('exp10', sa.String(length=255), nullable=True),
    sa.Column('exp11', sa.String(length=255), nullable=True),
    sa.Column('exp12', sa.String(length=255), nullable=True),
    sa.Column('exp13', sa.String(length=255), nullable=True),
    sa.Column('exp14', sa.String(length=255), nullable=True),
    sa.Column('exp15', sa.String(length=255), nullable=True),
    sa.Column('exp16', sa.String(length=255), nullable=True),
    sa.Column('exp17', sa.String(length=255), nullable=True),
    sa.Column('exp18', sa.String(length=255), nullable=True),
    sa.Column('exp19', sa.String(length=255), nullable=True),
    sa.Column('exp20', sa.String(length=255), nullable=True),
    sa.Column('title01', sa.String(length=255), nullable=True),
    sa.Column('title02', sa.String(length=255), nullable=True),
    sa.Column('title03', sa.String(length=255), nullable=True),
    sa.Column('title04', sa.String(length=255), nullable=True),
    sa.Column('title05', sa.String(length=255), nullable=True),
    sa.Column('title06', sa.String(length=255), nullable=True),
    sa.Column('title07', sa.String(length=255), nullable=True),
    sa.Column('title08', sa.String(length=255), nullable=True),
    sa.Column('title09', sa.String(length=255), nullable=True),
    sa.Column('title10', sa.String(length=255), nullable=True),
    sa.Column('title11', sa.String(length=255), nullable=True),
    sa.Column('title12', sa.String(length=255), nullable=True),
    sa.Column('title13', sa.String(length=255), nullable=True),
    sa.Column('title14', sa.String(length=255), nullable=True),
    sa.Column('title15', sa.String(length=255), nullable=True),
    sa.Column('title16', sa.String(length=255), nullable=True),
    sa.Column('title17', sa.String(length=255), nullable=True),
    sa.Column('title18', sa.String(length=255), nullable=True),
    sa.Column('title19', sa.String(length=255), nullable=True),
    sa.Column('title20', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('user_info')
    ### end Alembic commands ###
