from apps import db
from apps.utils import serialize


class People(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255),default="NULL")
    face = db.Column(db.String(255),default="NULL")
    exp01 = db.Column(db.String(255),default="NULL")
    exp02 = db.Column(db.String(255),default="NULL")
    exp03 = db.Column(db.String(255),default="NULL")
    exp04 = db.Column(db.String(255),default="NULL")
    exp05 = db.Column(db.String(255),default="NULL")
    exp06 = db.Column(db.String(255),default="NULL")
    exp07 = db.Column(db.String(255),default="NULL")
    exp08 = db.Column(db.String(255),default="NULL")
    exp09 = db.Column(db.String(255),default="NULL")
    exp10 = db.Column(db.String(255),default="NULL")
    exp11 = db.Column(db.String(255),default="NULL")
    exp12 = db.Column(db.String(255),default="NULL")
    exp13 = db.Column(db.String(255),default="NULL")
    exp14 = db.Column(db.String(255),default="NULL")
    exp15 = db.Column(db.String(255),default="NULL")
    exp16 = db.Column(db.String(255),default="NULL")
    exp17 = db.Column(db.String(255),default="NULL")
    exp18 = db.Column(db.String(255),default="NULL")
    exp19 = db.Column(db.String(255),default="NULL")
    exp20 = db.Column(db.String(255),default="NULL")
    title01 = db.Column(db.String(255),default="NULL")
    title02 = db.Column(db.String(255),default="NULL")
    title03 = db.Column(db.String(255),default="NULL")
    title04 = db.Column(db.String(255),default="NULL")
    title05 = db.Column(db.String(255),default="NULL")
    title06 = db.Column(db.String(255),default="NULL")
    title07 = db.Column(db.String(255),default="NULL")
    title08 = db.Column(db.String(255),default="NULL")
    title09 = db.Column(db.String(255),default="NULL")
    title10 = db.Column(db.String(255),default="NULL")
    title11 = db.Column(db.String(255),default="NULL")
    title12 = db.Column(db.String(255),default="NULL")
    title13 = db.Column(db.String(255),default="NULL")
    title14 = db.Column(db.String(255),default="NULL")
    title15 = db.Column(db.String(255),default="NULL")
    title16 = db.Column(db.String(255),default="NULL")
    title17 = db.Column(db.String(255),default="NULL")
    title18 = db.Column(db.String(255),default="NULL")
    title19 = db.Column(db.String(255),default="NULL")
    title20 = db.Column(db.String(255),default="NULL")

    @property
    def json(self):
        return serialize(self, self.__class__)

class User_info(db.Model):
    email = db.Column(db.String(255), primary_key=True)
    password = db.Column(db.String(255))
    name = db.Column(db.String(255))
    join_date = db.Column(db.DateTime(), default=db.func.now())
    introduce_myself = db.Column(db.Text())
    exp01 = db.Column(db.String(255),default="NULL")
    exp02 = db.Column(db.String(255),default="NULL")
    exp03 = db.Column(db.String(255),default="NULL")
    exp04 = db.Column(db.String(255),default="NULL")
    exp05 = db.Column(db.String(255),default="NULL")
    exp06 = db.Column(db.String(255),default="NULL")
    exp07 = db.Column(db.String(255),default="NULL")
    exp08 = db.Column(db.String(255),default="NULL")
    exp09 = db.Column(db.String(255),default="NULL")
    exp10 = db.Column(db.String(255),default="NULL")
    exp11 = db.Column(db.String(255),default="NULL")
    exp12 = db.Column(db.String(255),default="NULL")
    exp13 = db.Column(db.String(255),default="NULL")
    exp14 = db.Column(db.String(255),default="NULL")
    exp15 = db.Column(db.String(255),default="NULL")
    exp16 = db.Column(db.String(255),default="NULL")
    exp17 = db.Column(db.String(255),default="NULL")
    exp18 = db.Column(db.String(255),default="NULL")
    exp19 = db.Column(db.String(255),default="NULL")
    exp20 = db.Column(db.String(255),default="NULL")
    title01 = db.Column(db.String(255),default="NULL")
    title02 = db.Column(db.String(255),default="NULL")
    title03 = db.Column(db.String(255),default="NULL")
    title04 = db.Column(db.String(255),default="NULL")
    title05 = db.Column(db.String(255),default="NULL")
    title06 = db.Column(db.String(255),default="NULL")
    title07 = db.Column(db.String(255),default="NULL")
    title08 = db.Column(db.String(255),default="NULL")
    title09 = db.Column(db.String(255),default="NULL")
    title10 = db.Column(db.String(255),default="NULL")
    title11 = db.Column(db.String(255),default="NULL")
    title12 = db.Column(db.String(255),default="NULL")
    title13 = db.Column(db.String(255),default="NULL")
    title14 = db.Column(db.String(255),default="NULL")
    title15 = db.Column(db.String(255),default="NULL")
    title16 = db.Column(db.String(255),default="NULL")
    title17 = db.Column(db.String(255),default="NULL")
    title18 = db.Column(db.String(255),default="NULL")
    title19 = db.Column(db.String(255),default="NULL")
    title20 = db.Column(db.String(255),default="NULL")